name: Build STL Models

on:
  push:
    paths:
      - 'src/**/*.scad'
      - '.github/workflows/build-stl.yml'
  pull_request:
    paths:
      - 'src/**/*.scad'
      - '.github/workflows/build-stl.yml'

jobs:
  build-stl:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
      
    - name: Install OpenSCAD
      run: |
        sudo apt-get update
        sudo apt-get install -y openscad
        
    - name: Verify OpenSCAD installation
      run: openscad --version
      
    - name: Generate STL files
      run: |
        # Create output directory if it doesn't exist
        mkdir -p models
        
        # Generate STL files for all .scad files in src/
        for scad in src/*.scad; do
          base=$(basename "$scad" .scad)
          openscad -o "models/$base.stl" "$scad"
        done
        
    - name: Verify STL files were created
      run: |
        ls -la models/
        file models/*.stl
        
    - name: Upload STL artifacts
      uses: actions/upload-artifact@v4
      with:
        name: stl-models
        path: models/*.stl
        retention-days: 30
        
    - name: Commit updated STL files
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add models/*.stl
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Auto-generate STL files from OpenSCAD source

          Generated with GitHub Actions
          
          Co-Authored-By: GitHub Actions <action@github.com>"
          git push
        fi
      permissions:
        contents: write
